set(ROOT_DIR_SCRIPT ${CMAKE_CURRENT_SOURCE_DIR}/cmake)
set(ROOT_DIR_LIB    ${CMAKE_CURRENT_SOURCE_DIR}/lib)
set(ROOT_DIR        ${CMAKE_CURRENT_SOURCE_DIR})

if   (NOT EXISTS ${ROOT_DIR_LIB})
    file (MAKE_DIRECTORY ${ROOT_DIR_LIB})
endif()

include (cmake/preset.cmake)
include (cmake/opt.cmake)
include (cmake/git.cmake)
include (cmake/dep.cmake)
include (cmake/app.cmake)
include (cmake/lib.cmake)
include (cmake/inc.cmake)
include (cmake/asm.cmake)