macro   (detect_compiler)
    if     ("${CMAKE_C_COMPILER_ID}" MATCHES  "Clang")
        add_compile_definitions(PRESET_COMPILER_CLANG)
        add_compile_definitions(PRESET_COMPILER)
        add_compile_definitions(PRESET_FFI_SYSV)

        set(PRESET_COMPILER_CLANG on)
        set(PRESET_COMPILER       on)
        set(PRESET_FFI_SYSV       on)
    elseif ("${CMAKE_C_COMPILER_ID}" STREQUAL "GNU")
        add_compile_definitions(PRESET_COMPILER_GCC)
        add_compile_definitions(PRESET_COMPILER)
        add_compile_definitions(PRESET_FFI_SYSV)
        add_compile_options    (-Wno-incompatible-pointer-types)

        set(PRESET_COMPILER_GCC on)
        set(PRESET_COMPILER     on)
        set(PRESET_FFI_SYSV     on)
    elseif ("${CMAKE_C_COMPILER_ID}" STREQUAL "Intel")
        add_compile_definitions(PRESET_COMPILER_INTEL)
        add_compile_definitions(PRESET_COMPILER)
        add_compile_definitions(PRESET_FFI_SYSV)

        set(PRESET_COMPILER_INTEL on)
        set(PRESET_COMPILER       on)
        set(PRESET_FFI_SYSV       on)
    elseif ("${CMAKE_C_COMPILER_ID}" STREQUAL "MSVC")
        add_compile_definitions(PRESET_COMPILER_MSVC)
        add_compile_definitions(PRESET_COMPILER)
        add_compile_definitions(PRESET_FFI_VECTORCALL)

        set(PRESET_COMPILER_MSVC  on)
        set(PRESET_COMPILER       on)
        set(PRESET_FFI_VECTORCALL on)
    endif()
endmacro()