macro   (detect_os)
    if    (UNIX AND NOT APPLE)
        set                    (PRESET_LINUX ON)
        set                    (PRESET_OS    ON)
        add_compile_definitions(PRESET_LINUX)
    elseif(WIN32)
        set                    (PRESET_WIN32 ON)
        set                    (PRESET_OS    ON)
        add_compile_definitions(PRESET_WIN32)
    endif ()
endmacro()