macro   (app)
    cmake_parse_arguments (ARG "MISC" "NAME;OPT" "SRC;DEP;INC" ${ARGN})
    if   (NOT ARG_NAME)
        message("[cease] Application name must be specified.")
        message(SEND_ERROR)
    endif()

    add_executable (${ARG_NAME} ${ARG_SRC})
    if   (NOT ARG_SRC)
        message("[cease] Application source must be specified.")
        message(SEND_ERROR)
    endif()

    if   (ARG_INC)
        target_include_directories(${ARG_NAME} PUBLIC ${ARG_INC})
    endif()
    if   (ARG_DEP)
        target_link_libraries     (${ARG_NAME} PUBLIC ${ARG_DEP})
    endif()
endmacro()