if    (UNIX AND NOT APPLE)
        if    (NOT EXISTS "/usr/bin/git")
            message("No Git Installation Found")
            message(SEND_ERROR)
        endif ()
elseif(WIN32)
    if    (NOT EXISTS "C:/Program Files/Git/bin/git.exe")
        message("No Git Installation Found")
        message(SEND_ERROR "Abort")
    endif ()
endif()

function  (repo NAME AUTHOR VER)
    string(APPEND URL "https://github.com/${AUTHOR}/")
    string(APPEND DIR ${ROOT_LIB}/${NAME})

    if   (NOT EXISTS ${DIR})
        execute_process(COMMAND git clone ${URL}/${NAME} -b ${VER} WORKING_DIRECTORY ${ROOT_LIB})
    endif()

    if   (EXISTS ${DIR}/include)
        include_directories(${DIR}/include)
    endif()
    unset(AUTHOR)
    unset(PATH)
    unset(VER)
    unset(URL)
endfunction()