if    (UNIX AND NOT APPLE)
        if    (NOT EXISTS "/usr/bin/git")
            message("No Git Installation Found")
            message(SEND_ERROR)
        endif ()
elseif(WIN32)
    if    (NOT EXISTS "C:/Program Files/Git/bin/git.exe")
        message("No Git Installation Found")
        message(SEND_ERROR "Abort")
    endif ()
endif()

function  (repo NAME AUTHOR VER PATH)
    string(APPEND URL "https://github.com/${AUTHOR}/")
    if    (NOT EXISTS ${PATH}/${NAME})
        execute_process(COMMAND git clone ${URL}/${NAME} -b ${VER} WORKING_DIRECTORY ${PATH})
    endif ()

    unset (AUTHOR)
    unset (NAME)
    unset (PATH)
    unset (VER)
    unset (URL)
endfunction()