function   (use NAME)
    if   (NOT EXISTS ${ROOT_LIB}/${NAME})
        message("[cease] Library ${NAME} is not exist under ${ROOT_LIB}")
        message(SEND_ERROR)
    endif()
    set  (${NAME} ON PARENT_SCOPE)

    string(APPEND DIR ${ROOT_LIB}/${NAME})
    unset (NAME)
    if    (EXISTS ${DIR}/CMakeLists.txt)
        add_subdirectory(${DIR})
    endif ()
endfunction()